Added Duplicate Caption Button
capstone-team-a/Perception pull request #90
Opened 2019-12-04 01:23 UTC by plavabe12

Added a duplicate caption button

2019-12-04 02:12 UTC, JosephJindrich requested changes
Currently when you duplicate, if you have unsaved changes they automatically save, and are applied to the duplicated captions.

2019-12-04 02:12 UTC, JosephJindrich commented on src/client/src/models/Scene.js
> +    console.log("Hi")
Take this out please

2019-12-04 02:25 UTC, plavabe12 commented on src/client/src/models/Scene.js
> +    console.log("Hi")
Done

2019-12-04 02:25 UTC, plavabe12 commented
Code Cleaned Up

2019-12-04 07:01 UTC, JosephJindrich requested changes
Hitting Duplicate caption now takes me to a 404 not found page. Also hitting the duplicate button on the caption card causes the scene to duplicate instead of the caption.

2019-12-04 07:36 UTC, JosephJindrich commented
The comment about clicking the duplicate button taking me to a duplicated scene was wrong. Howver, it does take me to 404 not found.

2019-12-04 15:15 UTC, plavabe12 commented
@JosephJindrich bug appeared after taking out the saving function. Fixed.

2019-12-05 06:09 UTC, JosephJindrich approved these changes
Looks good

2019-12-05 06:10 UTC, merged